from enum import Enum


class VertexType(Enum):
    SESSION = "SESSION"
    MESSAGE = "MESSAGE"
    OPENING = "OPENING"
    SOURCE = "SOURCE"
    SINK = "SINK"
    CHANNEL = "CHANNEL"
    MANIPULATOR = "MANIPULATOR"
    MOVEMENT = "MOVEMENT"


class EdgeType(Enum):
    HAS_MESSAGE = "HAS_MESSAGE"
    NEXT_MESSAGE = "NEXT_MESSAGE"
    PRODUCES = "PRODUCES"
    CONSUMES = "CONSUMES"
    CONNECTS = "CONNECTS"
    ATTACHED_TO = "ATTACHED_TO"
    REQUIRES = "REQUIRES"
    CONTROLS = "CONTROLS"
    CONTAINS = "CONTAINS"
    HAS_OPENING = "HAS_OPENING"
    AFFORDS = "AFFORDS"
    ENABLES = "ENABLES"
