from enum import Enum


class VertexType(Enum):
    USER = "USER"
    CHARACTER = "CHARACTER"
    LOCATION = "LOCATION"
    PART = "PART"
    MESSAGE = "MESSAGE"
    OPENING = "OPENING"
    SOURCE = "SOURCE"
    SINK = "SINK"
    CHANNEL = "CHANNEL"
    MANIPULATOR = "MANIPULATOR"
    MOVEMENT = "MOVEMENT"


class EdgeType(Enum):
    HAS_MESSAGE = "HAS_MESSAGE"
    LAST_MESSAGE = "LAST_MESSAGE"
    NEXT_MESSAGE = "NEXT_MESSAGE"
    LOCATED_AT = "LOCATED_AT"
    CONNECTS = "CONNECTS"
    ATTACHED_TO = "ATTACHED_TO"
    PRODUCES = "PRODUCES"
    CONSUMES = "CONSUMES"
    REQUIRES = "REQUIRES"
    CONTROLS = "CONTROLS"
    CONTAINS = "CONTAINS"
    HAS_OPENING = "HAS_OPENING"
    AFFORDS = "AFFORDS"
    ENABLES = "ENABLES"
