from dataclasses import dataclass
from enum import StrEnum

from src.core.model.environment.climate.biome import Biome
from src.core.model.environment.weather.wind_intensity import WindIntensityEnum


class ParticulateTypeEnum(StrEnum):
    NONE = "none"
    DUST = "dust"
    SAND = "sand"
    ASH = "ash"
    SMOKE = "smoke"
    SPORES = "spores"
    POLLEN = "pollen"


@dataclass
class ParticulateTypeData:
    particulate_type: ParticulateTypeEnum


class ParticulateType:
    """Map biome and wind to airborne particulate matter."""

    particulate_type_grid: dict[tuple[Biome, WindIntensityEnum], ParticulateTypeEnum] = {
        # -- ICE_SHEET ---------------------------------------------------
        (Biome.ICE_SHEET, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.ICE_SHEET, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- POLAR_DESERT ------------------------------------------------
        (Biome.POLAR_DESERT, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.POLAR_DESERT, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.POLAR_DESERT, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SAND,
        (Biome.POLAR_DESERT, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SAND,
        (Biome.POLAR_DESERT, WindIntensityEnum.GALE): ParticulateTypeEnum.SAND,
        (Biome.POLAR_DESERT, WindIntensityEnum.STORM): ParticulateTypeEnum.SAND,
        (Biome.POLAR_DESERT, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SAND,
        # -- WINDFELL ----------------------------------------------------
        (Biome.WINDFELL, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.WINDFELL, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.WINDFELL, WindIntensityEnum.BREEZY): ParticulateTypeEnum.DUST,
        (Biome.WINDFELL, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.DUST,
        (Biome.WINDFELL, WindIntensityEnum.GALE): ParticulateTypeEnum.DUST,
        (Biome.WINDFELL, WindIntensityEnum.STORM): ParticulateTypeEnum.DUST,
        (Biome.WINDFELL, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.DUST,
        # -- FROST_BOG ---------------------------------------------------
        (Biome.FROST_BOG, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.FROST_BOG, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.FROST_BOG, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.FROST_BOG, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.FROST_BOG, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.FROST_BOG, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.FROST_BOG, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- ICE_MIRE ----------------------------------------------------
        (Biome.ICE_MIRE, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.ICE_MIRE, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- GLACIAL_MARGIN ----------------------------------------------
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.GLACIAL_MARGIN, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- MELTING_PACK ------------------------------------------------
        (Biome.MELTING_PACK, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.MELTING_PACK, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- COLD_DESERT -------------------------------------------------
        (Biome.COLD_DESERT, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.COLD_DESERT, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.COLD_DESERT, WindIntensityEnum.BREEZY): ParticulateTypeEnum.ASH,
        (Biome.COLD_DESERT, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.ASH,
        (Biome.COLD_DESERT, WindIntensityEnum.GALE): ParticulateTypeEnum.ASH,
        (Biome.COLD_DESERT, WindIntensityEnum.STORM): ParticulateTypeEnum.ASH,
        (Biome.COLD_DESERT, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.ASH,
        # -- DRY_TAIGA ---------------------------------------------------
        (Biome.DRY_TAIGA, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.DRY_TAIGA, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.DRY_TAIGA, WindIntensityEnum.BREEZY): ParticulateTypeEnum.DUST,
        (Biome.DRY_TAIGA, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.DUST,
        (Biome.DRY_TAIGA, WindIntensityEnum.GALE): ParticulateTypeEnum.DUST,
        (Biome.DRY_TAIGA, WindIntensityEnum.STORM): ParticulateTypeEnum.DUST,
        (Biome.DRY_TAIGA, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.DUST,
        # -- LICHEN_WOODLAND ---------------------------------------------
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.LICHEN_WOODLAND, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- OPEN_BOREAL -------------------------------------------------
        (Biome.OPEN_BOREAL, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.OPEN_BOREAL, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.OPEN_BOREAL, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.OPEN_BOREAL, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.OPEN_BOREAL, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.OPEN_BOREAL, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.OPEN_BOREAL, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- DENSE_TAIGA -------------------------------------------------
        (Biome.DENSE_TAIGA, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.BREEZY): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.GALE): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.STORM): ParticulateTypeEnum.NONE,
        (Biome.DENSE_TAIGA, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.NONE,
        # -- WET_BOREAL --------------------------------------------------
        (Biome.WET_BOREAL, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.WET_BOREAL, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.WET_BOREAL, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.WET_BOREAL, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.WET_BOREAL, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.WET_BOREAL, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.WET_BOREAL, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- MUSKEG_BOG --------------------------------------------------
        (Biome.MUSKEG_BOG, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MUSKEG_BOG, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MUSKEG_BOG, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.MUSKEG_BOG, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.MUSKEG_BOG, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.MUSKEG_BOG, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.MUSKEG_BOG, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- SAGEBRUSH_STEPPE --------------------------------------------
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.BREEZY): ParticulateTypeEnum.DUST,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.DUST,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.GALE): ParticulateTypeEnum.DUST,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.STORM): ParticulateTypeEnum.DUST,
        (Biome.SAGEBRUSH_STEPPE, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.DUST,
        # -- SHORTGRASS_PRAIRIE ------------------------------------------
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.BREEZY): ParticulateTypeEnum.DUST,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.DUST,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.GALE): ParticulateTypeEnum.DUST,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.STORM): ParticulateTypeEnum.DUST,
        (Biome.SHORTGRASS_PRAIRIE, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.DUST,
        # -- MIXED_PRAIRIE -----------------------------------------------
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.MIXED_PRAIRIE, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- DECIDUOUS_FOREST --------------------------------------------
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.DECIDUOUS_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- MOIST_TEMPERATE_FOREST --------------------------------------
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_TEMPERATE_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- COOL_RAINFOREST ---------------------------------------------
        (Biome.COOL_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.COOL_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- FEN_WETLAND -------------------------------------------------
        (Biome.FEN_WETLAND, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.FEN_WETLAND, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.FEN_WETLAND, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.FEN_WETLAND, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.FEN_WETLAND, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.FEN_WETLAND, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.FEN_WETLAND, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- BADLANDS ----------------------------------------------------
        (Biome.BADLANDS, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.BADLANDS, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.BADLANDS, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SAND,
        (Biome.BADLANDS, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SAND,
        (Biome.BADLANDS, WindIntensityEnum.GALE): ParticulateTypeEnum.SAND,
        (Biome.BADLANDS, WindIntensityEnum.STORM): ParticulateTypeEnum.SAND,
        (Biome.BADLANDS, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SAND,
        # -- CHAPARRAL ---------------------------------------------------
        (Biome.CHAPARRAL, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.CHAPARRAL, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.CHAPARRAL, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SMOKE,
        (Biome.CHAPARRAL, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SMOKE,
        (Biome.CHAPARRAL, WindIntensityEnum.GALE): ParticulateTypeEnum.SMOKE,
        (Biome.CHAPARRAL, WindIntensityEnum.STORM): ParticulateTypeEnum.SMOKE,
        (Biome.CHAPARRAL, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SMOKE,
        # -- WOODLAND_SAVANNA --------------------------------------------
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.WOODLAND_SAVANNA, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- EVERGREEN_OAK_FOREST ----------------------------------------
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.EVERGREEN_OAK_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- LAUREL_FOREST -----------------------------------------------
        (Biome.LAUREL_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.LAUREL_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.LAUREL_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.LAUREL_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.LAUREL_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.LAUREL_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.LAUREL_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- TEMPERATE_RAINFOREST ----------------------------------------
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.TEMPERATE_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- PEAT_MARSH --------------------------------------------------
        (Biome.PEAT_MARSH, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.PEAT_MARSH, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.PEAT_MARSH, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.PEAT_MARSH, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.PEAT_MARSH, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.PEAT_MARSH, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.PEAT_MARSH, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- SEMI_ARID_SHRUBLAND -----------------------------------------
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SMOKE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SMOKE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.GALE): ParticulateTypeEnum.SMOKE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.STORM): ParticulateTypeEnum.SMOKE,
        (Biome.SEMI_ARID_SHRUBLAND, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SMOKE,
        # -- THORN_SCRUB -------------------------------------------------
        (Biome.THORN_SCRUB, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.THORN_SCRUB, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.THORN_SCRUB, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SMOKE,
        (Biome.THORN_SCRUB, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SMOKE,
        (Biome.THORN_SCRUB, WindIntensityEnum.GALE): ParticulateTypeEnum.SMOKE,
        (Biome.THORN_SCRUB, WindIntensityEnum.STORM): ParticulateTypeEnum.SMOKE,
        (Biome.THORN_SCRUB, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SMOKE,
        # -- DRY_FOREST --------------------------------------------------
        (Biome.DRY_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.DRY_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.DRY_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.DRY_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.DRY_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.DRY_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.DRY_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- MARITIME_WOODLAND -------------------------------------------
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.MARITIME_WOODLAND, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- SUBTROPICAL_RAINFOREST --------------------------------------
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.SUBTROPICAL_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- WARM_RAINFOREST ---------------------------------------------
        (Biome.WARM_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.WARM_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- SWAMP_FOREST ------------------------------------------------
        (Biome.SWAMP_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SWAMP_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SWAMP_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.SWAMP_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.SWAMP_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.SWAMP_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.SWAMP_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- SAND_DESERT -------------------------------------------------
        (Biome.SAND_DESERT, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SAND_DESERT, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SAND_DESERT, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SAND,
        (Biome.SAND_DESERT, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SAND,
        (Biome.SAND_DESERT, WindIntensityEnum.GALE): ParticulateTypeEnum.SAND,
        (Biome.SAND_DESERT, WindIntensityEnum.STORM): ParticulateTypeEnum.SAND,
        (Biome.SAND_DESERT, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SAND,
        # -- SAVANNA_SCRUB -----------------------------------------------
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SMOKE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SMOKE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.GALE): ParticulateTypeEnum.SMOKE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.STORM): ParticulateTypeEnum.SMOKE,
        (Biome.SAVANNA_SCRUB, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SMOKE,
        # -- SEASONAL_FOREST ---------------------------------------------
        (Biome.SEASONAL_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.SEASONAL_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- MONSOON_RAINFOREST ------------------------------------------
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- TROPICAL_RAINFOREST -----------------------------------------
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.TROPICAL_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- WET_RAINFOREST ----------------------------------------------
        (Biome.WET_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.WET_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.WET_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.WET_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.WET_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.WET_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.WET_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- MANGROVE_SWAMP ----------------------------------------------
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.MANGROVE_SWAMP, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- SCORCHING_WASTELAND -----------------------------------------
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SAND,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SAND,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.GALE): ParticulateTypeEnum.SAND,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.STORM): ParticulateTypeEnum.SAND,
        (Biome.SCORCHING_WASTELAND, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SAND,
        # -- DRY_SAVANNA -------------------------------------------------
        (Biome.DRY_SAVANNA, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.DRY_SAVANNA, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.DRY_SAVANNA, WindIntensityEnum.BREEZY): ParticulateTypeEnum.DUST,
        (Biome.DRY_SAVANNA, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.DUST,
        (Biome.DRY_SAVANNA, WindIntensityEnum.GALE): ParticulateTypeEnum.DUST,
        (Biome.DRY_SAVANNA, WindIntensityEnum.STORM): ParticulateTypeEnum.DUST,
        (Biome.DRY_SAVANNA, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.DUST,
        # -- MONSOON_FOREST ----------------------------------------------
        (Biome.MONSOON_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MONSOON_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MONSOON_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.MONSOON_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- MOIST_FOREST ------------------------------------------------
        (Biome.MOIST_FOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.MOIST_FOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.MOIST_FOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_FOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_FOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_FOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.POLLEN,
        (Biome.MOIST_FOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.POLLEN,
        # -- LOWLAND_RAINFOREST ------------------------------------------
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.LOWLAND_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- EQUATORIAL_RAINFOREST ---------------------------------------
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.EQUATORIAL_RAINFOREST, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
        # -- FLOODED_JUNGLE ----------------------------------------------
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.CALM): ParticulateTypeEnum.NONE,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.GENTLE): ParticulateTypeEnum.NONE,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.BREEZY): ParticulateTypeEnum.SPORES,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.BLUSTERY): ParticulateTypeEnum.SPORES,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.GALE): ParticulateTypeEnum.SPORES,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.STORM): ParticulateTypeEnum.SPORES,
        (Biome.FLOODED_JUNGLE, WindIntensityEnum.HURRICANE): ParticulateTypeEnum.SPORES,
    }

    def get_particulate_type(
        self,
        biome_enum: Biome,
        wind_intensity_enum: WindIntensityEnum,
    ) -> ParticulateTypeEnum:
        """Look up particulate type for a biome and wind pair."""
        return self.particulate_type_grid.get(
            (biome_enum, wind_intensity_enum), ParticulateTypeEnum.NONE
        )

